language: elixir
elixir:
  - 1.6

install:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - cd example && mix deps.get && npm install
  - cd ..

before_script:
  - phantomjs -w &

script: mix test && cd example && WEBDRIVER=phantomjs MIX_ENV=test mix compile && mix test
